### PR TITLE
Update dagmc_slice_tool.py

### PR DESCRIPTION
**Pull request by AI-Pranto**
Edit dagmc_slice_tool.py

### CODE REVIEW

**Comment by pshriwise** [comment]
Hi @AI-Pranto - thanks for the PR!

I haven't touched this tool in a while now. Have you been successful in using it?

**Comment by AI-Pranto** [comment]
Yes, It works perfectly ok.

**Comment by pshriwise** [comment]
Great to hear. Thanks for trying it out!

**Review by pshriwise — APPROVED** [review]
These changes look good to me for an update to Python 3. Thanks @AI-Pranto!

**Pull request merged**
